$.ajax({
    url:'http://localhost:8080/BookAssitantSystem/login',
    type:"POST",
    data:{
        userName:'sjm',
        password:'12345',
        token:'12321421'
    },
    success:function(data){
        console.log(data);
    }
});